version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: session_recorder
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dev/seed:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  collector:
  
    build:
      context: .
      dockerfile: apps/collector/Dockerfile
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - SESSION_BUCKET=${SESSION_BUCKET}
    ports:
      - "3001:3001"
    depends_on:
      - redis

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/session_recorder
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
