services:
  - type: web
    name: screenshot-service
    env: docker
    rootDir: apps/screenshot-service
    dockerfilePath: ./Dockerfile
    plan: free
    scaling:
      minInstances: 1
      maxInstances: 1
    envVars:
      - key: NODE_OPTIONS
        value: "--max-old-space-size=384"
    limits:
      memory: 384
      maxConcurrency: 1
    healthCheckPath: /health
    healthCheckTimeout: 60 