import type { Metadata } from "next";
import "../globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import { Navbar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body
      >
        <SidebarProvider>
          <div className="flex w-full">
            <AppSidebar />
            <div className="flex-1 flex flex-col ml-[280px]">
              <Navbar />
              <main className="flex-1 pt-3 px-2">{children}</main>
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
