name = "session-recorder"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[build]
command = "pnpm build"
watch_dir = "src"

[site]
bucket = "./dist"
entry-point = "dist/tracker.js"

[vars]
ENVIRONMENT = "production"
API_URL = "https://gaha.vercel.app"

pages_build_output_dir = "dist"
